# binpass installed as `pass`.
#
# A bare symlink would be most of the way there — binpass reads argv[0] and
# presents itself under the name it was called by — but completions would
# still be missing, and completion is most of what makes a password manager
# usable at the prompt.
{
  lib,
  runCommand,
  binpass,
}:
runCommand "pass-${binpass.version}"
  {
    meta = binpass.meta // {
      description = "${binpass.meta.description} (installed as pass)";
      mainProgram = "pass";
    };

    passthru.binpass = binpass;
  }
  ''
    mkdir -p "$out/bin"
    ln -s ${lib.getExe binpass} "$out/bin/pass"

    # Generated by the shim itself, so the completion functions are named
    # after `pass` rather than after `binpass`. A script generated under one
    # name and installed under the other completes a command that is not
    # there.
    install -Dm444 <("$out/bin/pass" completion bash) \
      "$out/share/bash-completion/completions/pass"
    install -Dm444 <("$out/bin/pass" completion zsh) \
      "$out/share/zsh/site-functions/_pass"
    install -Dm444 <("$out/bin/pass" completion fish) \
      "$out/share/fish/vendor_completions.d/pass.fish"
  ''
