// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/remote/remote.go
//
// Generated by this command:
//
//	mockgen -source=pkg/remote/remote.go -destination=pkg/remote/mocks/remote_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	manifest "github.com/71g3pf4c3/binpass/pkg/manifest"
	remote "github.com/71g3pf4c3/binpass/pkg/remote"
	gomock "go.uber.org/mock/gomock"
)

// MockRemote is a mock of Remote interface.
type MockRemote struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteMockRecorder
	isgomock struct{}
}

// MockRemoteMockRecorder is the mock recorder for MockRemote.
type MockRemoteMockRecorder struct {
	mock *MockRemote
}

// NewMockRemote creates a new mock instance.
func NewMockRemote(ctrl *gomock.Controller) *MockRemote {
	mock := &MockRemote{ctrl: ctrl}
	mock.recorder = &MockRemoteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemote) EXPECT() *MockRemoteMockRecorder {
	return m.recorder
}

// Caps mocks base method.
func (m *MockRemote) Caps() remote.Caps {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Caps")
	ret0, _ := ret[0].(remote.Caps)
	return ret0
}

// Caps indicates an expected call of Caps.
func (mr *MockRemoteMockRecorder) Caps() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Caps", reflect.TypeOf((*MockRemote)(nil).Caps))
}

// Close mocks base method.
func (m *MockRemote) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRemoteMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRemote)(nil).Close))
}

// CommitManifest mocks base method.
func (m_2 *MockRemote) CommitManifest(ctx context.Context, m *manifest.Signed, expect uint64) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "CommitManifest", ctx, m, expect)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitManifest indicates an expected call of CommitManifest.
func (mr *MockRemoteMockRecorder) CommitManifest(ctx, m, expect any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitManifest", reflect.TypeOf((*MockRemote)(nil).CommitManifest), ctx, m, expect)
}

// DeleteObjects mocks base method.
func (m *MockRemote) DeleteObjects(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjects", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjects indicates an expected call of DeleteObjects.
func (mr *MockRemoteMockRecorder) DeleteObjects(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjects", reflect.TypeOf((*MockRemote)(nil).DeleteObjects), ctx, ids)
}

// GetObject mocks base method.
func (m *MockRemote) GetObject(ctx context.Context, id string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, id)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockRemoteMockRecorder) GetObject(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockRemote)(nil).GetObject), ctx, id)
}

// HasObjects mocks base method.
func (m *MockRemote) HasObjects(ctx context.Context, ids []string) (map[string]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasObjects", ctx, ids)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasObjects indicates an expected call of HasObjects.
func (mr *MockRemoteMockRecorder) HasObjects(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasObjects", reflect.TypeOf((*MockRemote)(nil).HasObjects), ctx, ids)
}

// Manifest mocks base method.
func (m *MockRemote) Manifest(ctx context.Context) (*manifest.Signed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Manifest", ctx)
	ret0, _ := ret[0].(*manifest.Signed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Manifest indicates an expected call of Manifest.
func (mr *MockRemoteMockRecorder) Manifest(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Manifest", reflect.TypeOf((*MockRemote)(nil).Manifest), ctx)
}

// Name mocks base method.
func (m *MockRemote) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockRemoteMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockRemote)(nil).Name))
}

// PutObject mocks base method.
func (m *MockRemote) PutObject(ctx context.Context, id string, r io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, id, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutObject indicates an expected call of PutObject.
func (mr *MockRemoteMockRecorder) PutObject(ctx, id, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockRemote)(nil).PutObject), ctx, id, r)
}
