// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/sync/engine.go
//
// Generated by this command:
//
//	mockgen -source=pkg/sync/engine.go -destination=pkg/sync/mocks/engine_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	ed25519 "crypto/ed25519"
	reflect "reflect"

	manifest "github.com/71g3pf4c3/binpass/pkg/manifest"
	gomock "go.uber.org/mock/gomock"
)

// MockLocal is a mock of Local interface.
type MockLocal struct {
	ctrl     *gomock.Controller
	recorder *MockLocalMockRecorder
	isgomock struct{}
}

// MockLocalMockRecorder is the mock recorder for MockLocal.
type MockLocalMockRecorder struct {
	mock *MockLocal
}

// NewMockLocal creates a new mock instance.
func NewMockLocal(ctrl *gomock.Controller) *MockLocal {
	mock := &MockLocal{ctrl: ctrl}
	mock.recorder = &MockLocalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocal) EXPECT() *MockLocalMockRecorder {
	return m.recorder
}

// ApplyDeletion mocks base method.
func (m *MockLocal) ApplyDeletion(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyDeletion", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyDeletion indicates an expected call of ApplyDeletion.
func (mr *MockLocalMockRecorder) ApplyDeletion(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyDeletion", reflect.TypeOf((*MockLocal)(nil).ApplyDeletion), path)
}

// BuildManifest mocks base method.
func (m *MockLocal) BuildManifest(base *manifest.Manifest) (*manifest.Manifest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildManifest", base)
	ret0, _ := ret[0].(*manifest.Manifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildManifest indicates an expected call of BuildManifest.
func (mr *MockLocalMockRecorder) BuildManifest(base any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildManifest", reflect.TypeOf((*MockLocal)(nil).BuildManifest), base)
}

// DeviceID mocks base method.
func (m *MockLocal) DeviceID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceID")
	ret0, _ := ret[0].(string)
	return ret0
}

// DeviceID indicates an expected call of DeviceID.
func (mr *MockLocalMockRecorder) DeviceID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceID", reflect.TypeOf((*MockLocal)(nil).DeviceID))
}

// EntryObject mocks base method.
func (m *MockLocal) EntryObject(path string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EntryObject", path)
	ret0, _ := ret[0].(string)
	return ret0
}

// EntryObject indicates an expected call of EntryObject.
func (mr *MockLocalMockRecorder) EntryObject(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EntryObject", reflect.TypeOf((*MockLocal)(nil).EntryObject), path)
}

// HasEntry mocks base method.
func (m *MockLocal) HasEntry(path string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasEntry", path)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasEntry indicates an expected call of HasEntry.
func (mr *MockLocalMockRecorder) HasEntry(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasEntry", reflect.TypeOf((*MockLocal)(nil).HasEntry), path)
}

// ReadObject mocks base method.
func (m *MockLocal) ReadObject(id string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadObject", id)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadObject indicates an expected call of ReadObject.
func (mr *MockLocalMockRecorder) ReadObject(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadObject", reflect.TypeOf((*MockLocal)(nil).ReadObject), id)
}

// SigningKey mocks base method.
func (m *MockLocal) SigningKey() (ed25519.PrivateKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SigningKey")
	ret0, _ := ret[0].(ed25519.PrivateKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SigningKey indicates an expected call of SigningKey.
func (mr *MockLocalMockRecorder) SigningKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SigningKey", reflect.TypeOf((*MockLocal)(nil).SigningKey))
}

// StoreID mocks base method.
func (m *MockLocal) StoreID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreID")
	ret0, _ := ret[0].(string)
	return ret0
}

// StoreID indicates an expected call of StoreID.
func (mr *MockLocalMockRecorder) StoreID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreID", reflect.TypeOf((*MockLocal)(nil).StoreID))
}

// WriteConflictCopy mocks base method.
func (m *MockLocal) WriteConflictCopy(path string, ciphertext []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteConflictCopy", path, ciphertext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteConflictCopy indicates an expected call of WriteConflictCopy.
func (mr *MockLocalMockRecorder) WriteConflictCopy(path, ciphertext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteConflictCopy", reflect.TypeOf((*MockLocal)(nil).WriteConflictCopy), path, ciphertext)
}

// WriteObject mocks base method.
func (m *MockLocal) WriteObject(path, id string, ciphertext []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteObject", path, id, ciphertext)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteObject indicates an expected call of WriteObject.
func (mr *MockLocalMockRecorder) WriteObject(path, id, ciphertext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteObject", reflect.TypeOf((*MockLocal)(nil).WriteObject), path, id, ciphertext)
}

// MockState is a mock of State interface.
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
	isgomock struct{}
}

// MockStateMockRecorder is the mock recorder for MockState.
type MockStateMockRecorder struct {
	mock *MockState
}

// NewMockState creates a new mock instance.
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// LoadBase mocks base method.
func (m *MockState) LoadBase() (*manifest.Manifest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadBase")
	ret0, _ := ret[0].(*manifest.Manifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadBase indicates an expected call of LoadBase.
func (mr *MockStateMockRecorder) LoadBase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadBase", reflect.TypeOf((*MockState)(nil).LoadBase))
}

// SaveBase mocks base method.
func (m_2 *MockState) SaveBase(m *manifest.Manifest) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SaveBase", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBase indicates an expected call of SaveBase.
func (mr *MockStateMockRecorder) SaveBase(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBase", reflect.TypeOf((*MockState)(nil).SaveBase), m)
}
